### ISSUE TITLE
Seeking explanation of the re-org from Pull Request #7

### ISSUE THREAD

**Issue by gregelin** [18F/control-masonry#10]
@ramirezg Pull Request #7 culminated a fairly significant reorganization of the files. What follows is my understanding of the changes. Can you tell me if they are correct?

1. Replaced the `controls` directory of YAML documents with (1) `data` directory of YAML and (2) `completed_certifications` directory.
2. This new structure replaces the `base_control.yaml`, `final_controler.yaml`, and `project_info.yaml` files with a better organized hierarchy of directories for source YAML files describing controls from system components.
3. The source YAML control files can actually be generated from source spreadsheets using `workbook_to_yamls.py`, which addresses importing controls from the many people who currently have controls listed in spreadsheets.
4. Instead of generating `final_controler.yaml` as the interim YAML file from which to generate the control markdown pages for Jekyll, there is a new python script, `yamls_to_certification.py`, that generates "certification" YAML files in `completed_certifications`.

I'm assuming the markdown pages can still be served with Jekyll, but the repo at the moment is missing the javascript scripts that previously existed to generate the markdown files. Is the idea to generate the markdown files using python script instead?

**Comment by mogul** [comment]
I think you've covered it pretty thoroughly... (It looks like you already found this based on issue #11, but an outline of our thinking is in issue #2.) @ramirezg can you comment?

**Comment by ramirezg** [comment]
@gregelin You're absolutely right, we should have been clearer. Like @mogul said you covered the changes thoroughly. Just to add a little more background, the changes you're seeing grew out of a fundamental shift in philosophy. 

Originally, the documentation centered the NIST-800-53 controls, which tied Control-masonry to a generic SSP. The new format centers components, which facilitates documentation for various certifications that go beyond NIST and documentation that engineers can better understand. 

We also moved to Python because it's more accessible/clearer for data tasks. Soon, we will reconnect the markdown pages, but right now our priority is defining the documentation and its format.

**Comment by gregelin** [comment]
@mogul @ramirezg Thanks for confirming.
